### PR TITLE
added logging via hpfeeds

### PR DESCRIPTION
**Pull request by vorband**
I added hpfeeds support for your ciscoasa_honeypot.

If hpfeeds shall be enabled, you must set either
a) the following environment variables
HPFEEDS_SERVER, HPFEEDS_PORT, HPFEEDS_IDENT, HPFEEDS_SECRET,
HPFEEDS_CHANNEL, SERVERID
or
b) add corresponding arguments --hpfserver, --hpfport, --hpfident,
--hpfsecret, --hpfchannel, --serverid (eq. id/name)

In case they are not set, it will behave as before and only log
locally/stdout.

Hope you find it useful and accept the pull request. Cheers.

### CODE REVIEW

**Comment by omercnet** [comment]
hi @vorband thanks for the PR!

We'll be porting this honeypot over to our new honeypot framework https://github.com/Cymmetria/honeycomb

would you mind converting this to an honeycomb integration? We'll also continue development of ciscoasa honeypot there

**Comment by vorband** [comment]
I will take a look at it as soon as I find the time. 
Do you have a modular or centralized logging function?

**Comment by omercnet** [comment]
in Honeycomb you get a simple alert dict with all the relevant fields that you can handle

check out https://github.com/Cymmetria/honeycomb_plugins/blob/master/integrations/json_file/integration.py#L17 as a good sample

check out the full API docs at http://honeycomb.cymmetria.com/projects/honeycomb-plugins/en/latest/integration_api.html we'll have a dev guide for integrations soon

**Comment by vorband** [comment]
For the time being, it would be great if you could accept the pull for this repo, so we can clone directly from the official repo. I will look into the hpfeeds plugin for honeycomb later.

**Comment by t3chn0m4g3** [comment]
@omercnet Please merge. Thank you.

**Review by omercnet — APPROVED** [review]

**Review by omercnet — CHANGES_REQUESTED** [review]
Please update README to include HPFeeds

**Review by omercnet — APPROVED** [review]

**Comment by t3chn0m4g3** [comment]
Thank you @omercnet @vorband

**Comment by vorband** [comment]
thank you @omercnet

**Pull request merged**
